### ISSUE TITLE
不能编译ipq807x-64

### ISSUE THREAD

**Issue by kob** [Leo357449107/qsdk_cmiot-ax6#1]
试着选择了ipq807x-64,发现编译报错
`make[4]: Entering directory '/home/kob/build2/qsdk_cmiot-ax6/build_dir/target-aarch64_cortex-a53_musl-1.1.16/linux-ipq_ipq807x_64/lk-af-ipq6018/lk-af-'
makefile:117: arch/arm64/rules.mk: No such file or directory`

**Comment by Leo357449107** [comment]
64位不能编译u-boot相关package
