### ISSUE TITLE
download from http://qcawebsrvr.qualcomm.com

### ISSUE THREAD

**Issue by rmandrad** [Leo357449107/qsdk_cmiot-ax6#3]
Hi,

all my builds are failing at the point of downloading the nss firmwares ... how do you go around the issue that http://qcawebsrvr.qualcomm.com is not available?

**Comment by Leo357449107** [comment]
11.5&12.xx nss fw is nonfree，but you can get 11.4 at "https://github.com/quic/qca-sdk-nss-fw/tree/main/QCA_Networking_2021.SPF_11.4/CS"。
unselect nss package and put the files to "files/lib/firmware".
or use package "https://github.com/coolsnowwolf/lede/tree/master/package/qca/firmware/nss-firmware"
